<?php 
Configure::write("", "");
Configure::write("Home.title1", "Welcome to the Social Platform <br> That Revolutionizes Calendar Sharing");
Configure::write("Home.title10", "You will have the ability to seamlessly add events to your personal calendar as well as share events with other calendars that you follow in quick and effortless manner.");
Configure::write("Home.title11", "Discover");
Configure::write("Home.title12", "Discover new calendars across the globe, locally, and based off of your interests. It is a quick and easy way to find new calendars with events that interests you while providing an enjoyable experience.");
Configure::write("Home.title2", "Our Features");
Configure::write("Home.title3", "Featured Calendars");
Configure::write("Home.title4", "<h2>Get this in <br> your pocket</h2> <h5>Download the App Today!</h5>");
Configure::write("Home.title5", "Calendar Manager");
Configure::write("Home.title6", "You can integrate all of your personal calendars that you use daily from various platforms on to this platform in a smooth and seamless way.");
Configure::write("Home.title7", "Instant Alert");
Configure::write("Home.title8", "All of the calendars that you follow, either private or public, will have the ability to push you alerts for events coming up if you grant permission through your notifications in your settings.");
Configure::write("Home.title9", "Calendar Sharing");
Configure::write("Payment.category1", "10");
Configure::write("Payment.category2", "50");
Configure::write("Payment.category3", "200");
Configure::write("Payment.featured1", "25");
Configure::write("Payment.featured2", "100");
Configure::write("Payment.featured3", "500");
Configure::write("Payment.local1", "10");
Configure::write("Payment.local2", "50");
Configure::write("Payment.local3", "200");
Configure::write("Payment.Verify", "1");
Configure::write("Site.admin_avatar", "1479881710_USA+v+Australia+FIVB+Men+Volleyball+World+3J59MfujikAl.jpg");
Configure::write("Site.AppStore", "mynuserybazaar");
Configure::write("Site.avatar_image", "1473060290_Olympics+Day+14+Volleyball+NcB7rIFtxfml.jpg");
Configure::write("Site.email_send_mail", "kiplphp53@gmail.com");
Configure::write("Site.facebook", "https://www.facebook.com/mynuserybazaar");
Configure::write("site.google", "https://twitter.com/mynuserybazaar");
Configure::write("Site.PlayStore", "mynuserybazaar");
Configure::write("Site.title", "MyNurseryBazaar");
Configure::write("site.twitter", "https://twitter.com/mynuserybazaar");
Configure::write("Site.video", "");
